### ISSUE TITLE
HitBox Hull's

### ISSUE THREAD

**Issue by C0nw0nk** [JetBoom/zombiesurvival#143]
So this problem has been around for months now but i see nobody made a post.

But the hitbox on humans crouching and zombies crouching can not be hit.

http://gmodwiki.net/Lua/Classes/Player/SetHull
http://gmodwiki.net/Lua/Classes/Player/SetHullDuck

**Comment by Zverina** [comment]
I never thought this was something that could be altered. I just figured the hitboxes were fucking garbage because it is Gmod.

Please, please, please make this a priority fix. A human's hitbox is actually lowered to half of his body when crouching-- the (almost) entire upper half of his body is non-solid and zombies cannot hit it.

**Comment by C0nw0nk** [comment]
It can be fixed very easly just by modifying the hull's. View the Gmod wiki links i pasted.

**Comment by JetBoom** [comment]
This was fixed in a previous gmod update: http://www.garrysmod.com/updates/
"util.TraceLine now hits player hitboxes outside of collision bounds"

Either way changing the hulls to match to the models would make you unable to duck under most things.

**Comment by foxhound1486** [comment]
JetBoom I dont want to be rude but you may want to test the hitboxs. Because even after the update it still doesnt work well enough to hit humans.

**Comment by JetBoom** [comment]
Bullets hit fine. The problem is traceline and tracehull don't call upon the engine UTIL_ClipTraceToPlayers function. Only bullets do. Converting zombie attacks to invisible bullets would probably "solve" it but it's such a hacky work around.

**Comment by C0nw0nk** [comment]
Whe you say bullets hit fine for a standing zombies it seems to be fine, Shooting crouching Fast Zombies in the head does nothing nor with crossbow bolts. The shade crouching also does not take damage if hes crouching behind something as small as a chair. I have not tested crouching headcrabs fleshcreepers etc.

**Comment by JetBoom** [comment]
Most zombies that don't have crouch animations aren't allowed to crouch. I'm not sure if that's in the version on github but I definitely have it locally.

I tested it and bullets hit everything fine, including fast zombies. Crossbow bolts aren't bullets and they have insanely big hit detection.

I've made a temporary workaround for melee (all I could see being broken). It's not elegant, so expect it to be wonky. I've tested it on a listen server and it works though.

**Comment by C0nw0nk** [comment]
Thanks i tested and it seems to work well :+1: Thanks for the update and quick reply :)

**Comment by ForrestMarkX** [comment]
Wouldn't you just use a TraceLine and TraceHull with the MASK_SHOT_HULL mask?

**Comment by JetBoom** [comment]
That's for the hit contents mask so no, not at all.

**Comment by ForrestMarkX** [comment]
Hmm well that's lovely seeing gmod breaking things again and needing hacky methods to get around it
